name: CI_CD_PIPELINE
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
      - name: Install PipEnv
        run: pip install pipenv --user
      - name: Install Dependencies
        run: pipenv sync --system --dev
      - name: Run Pytest with Coverage
        run: pytest --cov-report term --cov=football_data tests/
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PipEnv
        run: pip install pipenv --user
      - name: Install Dependencies
        run: pipenv sync --system --dev
      - name: MyPy
        run: mypy football_data/ --ignore-missing-imports
      - name: PyLint
        run: pylint football_data/
      - name: PyCodestyle
        run: pycodestyle football_data/ --max-line-length 100
      - name: PyFlakes
        run: pyflakes football_data/
      - name: Bandit
        run: bandit -r football_data/

  test_deploy:
    name: Upload release to Test PyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/legacy/batch-football-data
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Build
        run: pip install --upgrade build
      - name: Build Deployments
        run: python -m build
    # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PY_PI }}
          repository-url: https://test.pypi.org/legacy/
