name: CI_CD_PIPELINE
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run Tests
        run: uv run pytest tests

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run MyPy
        run: uv run mypy football_data/ --ignore-missing-imports
      - name: Run Flake8
        run: uv run flake8 football_data/ --max-line-length 100
      - name: Run Pyflakes
        run: uv run pyflakes football_data/
      - name: Run PyCodeStyle
        run: uv run pycodestyle football_data/ --max-line-length 100
      - name: Run Pylint
        run: uv run pylint football_data/
      - name: Run Bandit
        run: uv run bandit -r football_data/ -c ./pyproject.toml
    needs:
      - test
  test_deploy:
    name: Upload release to Test PyPI
    runs-on: ubuntu-latest
    needs: [test, static_analysis]
    environment:
      name: testpypi
      url: https://test.pypi.org/legacy/batch-football-data
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install Build
        run: pip install --upgrade build
      - name: Build Deployments
        run: python -m build
    # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PY_PI }}
          repository-url: https://test.pypi.org/legacy/

