name: DATA_PIPELINE_TESTS
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
      - name: Install PipEnv
        run: pip install pipenv --user
      - name: Install Dependencies
        run: pipenv sync --system --dev
      - name: Run Pytest with Coverage
        run: pytest --cov-report term --cov=football_data tests/